name: AWS DEPLOY TO STAGING (React Frontend)

on:
  push:
    branches:
      - main


jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: "ec2-3-90-176-226.compute-1.amazonaws.com"
          REMOTE_USER: Administrator
          TARGET: "C:/xampp/htdocs/travel-frontend"
