name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - run: chmod +x node_modules/.bin/react-scripts
        working-directory: frontend


      - name: Build project
        run: npm run build
        working-directory: frontend


      - name: Deploy to EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -rltgoDzvO --delete
          legacy_allow_rsa_hostkeys: "true"  
          path: build/
          remote_path: C:/xampp/htdocs/frontend
          remote_host: ec2-3-90-176-226.compute-1.amazonaws.com
          remote_user: Administrator
          remote_key: ${{ secrets.SERVER_SSH_KEY }}        
          
