name: React Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        # This will now run from within your 'frontend' folder.
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        # This will also run from within your 'frontend' folder.
        working-directory: ./frontend

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@v2.1.1
        with:
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          args: "-rltgoDzvO --delete"
          # The source is now correct to point to the 'build' folder inside 'frontend'.
          source: "frontend/build/"
          remote_host: "ec2-3-90-176-226.compute-1.amazonaws.com"
          remote_user: "Administrator"
          target: "C:/xampp/htdocs/travel-frontend"
