name: React Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    # This specifies the runner to use for the job. Ubuntu is fine for this task.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        # This command runs from the frontend directory of your project.
        run: npm install
        working-directory: ./frontend

      - name: Build project
        # This command also runs from the frontend directory.
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@v2.1.1
        with:
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          args: "-rltgoDzvO --delete"
          # The source directory is now explicitly set to the 'build' folder inside 'frontend'.
          source: "frontend/build/"
          remote_host: "ec2-3-90-176-226.compute-1.amazonaws.com"
          remote_user: "Administrator"
          # The target is the correct path on your Windows server.
          target: "C:/xampp/htdocs/travel-frontend"
